# Generated by Django 5.1.3 on 2026-02-22 20:05

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('tools', 'Tools & Equipment'), ('other', 'Other Inputs')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_input_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInputCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('quality_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.qualityinput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('quality_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.qualityinput')),
            ],
        ),
        migrations.CreateModel(
            name='QualityInputOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_input_orders', to=settings.AUTH_USER_MODEL)),
                ('quality_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.qualityinput')),
            ],
        ),
        migrations.CreateModel(
            name='QualityInputReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.qualityinput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
